# Generated by Django 2.1.7 on 2019-07-11 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, default='No se indica', max_length=50, null=True)),
                ('telefono', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Propietario', 'Propietario'), ('Normal', 'Normal')], default='Normal', max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_estacionamiento/%Y/%m/%d')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado')], default='Normal', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
